name: TWRP-Borneo-Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Afficher l’espace disque avant nettoyage
    - name: Check disk space (before cleanup)
      run: df -h

    # 2. Nettoyage agressif du disque
    - name: Aggressive disk cleanup
      run: |
        sudo rm -rf \
          /usr/share/dotnet \
          /usr/local/lib/android \
          /opt/ghc \
          /opt/hostedtoolcache \
          /usr/lib/jvm \
          /usr/local/share/boost \
          /usr/share/swift \
          /usr/lib/google-cloud-sdk

    # 3. Afficher l’espace disque après nettoyage
    - name: Check disk space (after cleanup)
      run: df -h

    # 4. Installer les outils nécessaires
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install git wget curl build-essential ccache repo -y
        ccache -M 5G

    # 5. Cloner les sources AOSP TWRP
    - name: Clone TWRP sources
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        mkdir -p ~/twrp && cd ~/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
        repo sync -j4 --no-clone-bundle --current-branch | while read line; do echo "[$(date)] $line"; done

    # 6. Supprimer .repo pour libérer de l'espace
    - name: Delete .repo after repo sync
      run: |
        cd ~/twrp
        rm -rf .repo

    # 7. Cloner le device tree Motorola Borneo
    - name: Clone Borneo device tree
      run: |
        cd ~/twrp
        mkdir -p device/motorola
        git clone -b twrp-android-11 https://github.com/touchpro/twrp_device_motorola_borneo device/motorola/borneo

    # 8. Compiler TWRP
    - name: Build TWRP recovery.img
      run: |
        cd ~/twrp
        export USE_CCACHE=1
        source build/envsetup.sh
        lunch twrp_borneo-eng
        mka recoveryimage | tee build.log

    # 9. Upload du recovery.img
    - name: Upload recovery.img
      uses: actions/upload-artifact@v4
      with:
        name: twrp-borneo
        path: ~/twrp/out/target/product/borneo/recovery.img

    # 10. Upload du build log
    - name: Upload build log
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: ~/twrp/build.log

    # 11. Push du recovery.img dans une branche du repo
    - name: Push recovery.img to output-recovery branch
      run: |
        cd ~/twrp/out/target/product/borneo
        git init
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout -b output-recovery
        git add recovery.img
        git commit -m "✅ Auto-built TWRP recovery for Borneo - $(date +'%Y-%m-%d %H:%M')"
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git push -f origin output-recovery
