name: TWRP-Borneo-Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install git wget curl build-essential -y

    - name: Clone TWRP sources
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        mkdir -p ~/twrp && cd ~/twrp
        sudo apt install repo -y
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
        repo sync -j4 --no-clone-bundle --current-branch | while read line; do echo "[$(date)] $line"; done

    - name: Clone Borneo device tree
      run: |
        cd ~/twrp
        mkdir -p device/motorola
        git clone -b twrp-android-11 https://github.com/touchpro/twrp_device_motorola_borneo device/motorola/borneo

    - name: Build TWRP
      run: |
        cd ~/twrp
        source build/envsetup.sh
        lunch twrp_borneo-eng
        mka recoveryimage

    - name: Upload recovery.img
      uses: actions/upload-artifact@v4
      with:
        name: twrp-borneo
        path: ~/twrp/out/target/product/borneo/recovery.img
